image: Visual Studio 2019 Preview

before_build:
  - nuget restore sem2/homework7/GUICalculator/GUICalculator.sln
  - choco install dotnetcore-sdk --pre

build_script:
  dotnet build sem2/homework7/GUICalculator/GUICalculator.sln