image: Visual Studio 2017

before_build:
  - nuget restore sem2/homework4/ParseTree/ParseTree.sln

build:
  project: sem2/homework4/ParseTree/ParseTree.sln

test_script:
  - dotnet test sem2/homework4/ParseTree/ParseTree.sln