image: Visual Studio 2017

before_build:
  - nuget restore sem2/homework6/ListMethods/ListMethods.sln

build:
  project: sem2/homework6/ListMethods/ListMethods.sln

test_script:
  - nunit3-console sem2/homework6/ListMethods/ListMethods.sln \
     --result=myresults.xml;format=AppVeyor