image: Visual Studio 2019

environment:
  matrix:
  - solution_path: sem4\SpecifiedAccuracy\SpecifiedAccuracy.sln

before_build:
 - nuget restore %solution_path%

build_script:
  - msbuild %solution_path%

test_script:
  - dotnet test sem4\SpecifiedAccuracy\SpecifiedAccuracyTests\SpecifiedAccuracy.Tests.fsproj