image: Visual Studio 2019

environment:
  matrix:
  - solution_path: sem4\Factorial\Factorial.sln
  - solution_path: sem4/ParseTree/ParseTree.sln
  - solution_path: Tests\Task1\Task1.sln

before_build:
  - nuget restore %solution_path%

build_script:
  - msbuild %solution_path%

test_script:
  - dotnet test sem4\Factorial\Factorial.Tests\Factorial.Tests.fsproj
  - dotnet test sem4\ParseTree\ParseTree.Tests\ParseTree.Tests.fsproj
  - dotnet test Tests\Task1\Task1\Task1.fsproj
