image: Visual Studio 2019

before_build:
  - nuget restore sem2/homework1/Factorial/Factorial.sln

build:
  project: sem2/homework1/Factorial/Factorial.sln

test_script:
  - dotnet test sem2/homework1/Factorial/Factorial.sln