image: Visual Studio 2017

before_build:
  - nuget restore sem2/homework7/Clock/Clock.sln

build:
  project: sem2/homework7/Clock/Clock.sln

test_script:
  - dotnet test sem2/homework7/Clock/Clock.sln