os: Visual Studio 2019 Preview

environment:
  CLI_VERSION: SDK 3.0.100-preview3-010431

install:
  - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
  - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
  - ps: Invoke-WebRequest -Uri "https://dotnet.microsoft.com/download/thank-you/dotnet-sdk-3.0.100-preview3-windows-x86-installer" -OutFile "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1"
  - ps: '& "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1" -Version $env:CLI_VERSION -InstallDir $env:DOTNET_INSTALL_DIR'
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"

build_script:
  # dotnet info
  - ps: dotnet --info
  # Run dotnet new
  - ps: mkdir "test\test-dotnet-new" -Force | Push-Location
  - ps: dotnet new console -lang c#
  - ps: dotnet restore
  - ps: dotnet build
  - ps: dotnet run a b
  - ps: Pop-Location


test: off
version: 0.0.1.{build}

image: Visual Studio 2019 Preview

before_build:
  - nuget restore sem2/homework4/ParseTree/ParseTree.sln

build:
  project: sem2/homework4/ParseTree/ParseTree.sln

test_script:
  - dotnet test sem2/homework4/ParseTree/ParseTree.sln