image: Visual Studio 2019

environment:
  matrix:
  - solution_path: sem4\Factorial\Factorial.sln
  - solution_path: sem4\InfinitePrimes\InfinitePrimes.sln

before_build:
  - nuget restore %solution_path%

build_script:
  - msbuild %solution_path%

test_script:
  - dotnet test sem4\Factorial\Factorial.Tests\Factorial.Tests.fsproj
  - dotnet test sem4\InfinitePrimes\InfinitePrimes.Tests\InfinitePrimes.Tests.fsproj
