image: Visual Studio 2019 Preview

before_build:
  - nuget restore sem2/homework3/Hash-Table/Hash-Table.sln
  - choco install dotnetcore-sdk --pre

build:
  dotnet build sem2/homework3/Hash-Table/Hash-Table.sln

test_script:
  - dotnet test sem2/homework3/Hash-Table/Hash-Table.sln