image: Visual Studio 2019

before_build: 
  - dotnet restore [<ROOT>] [--configfile] [--disable-parallel]
      [--force] [--ignore-failed-sources] [--no-cache]
      [--no-dependencies] [--packages]
  
environment:
  matrix:
  - solution_path: sem2/homework1/Factorial/Factorial.sln
  - solution_path: sem2/homework1/Fibonacci/Fibonacci.sln
  - solution_path: sem2/homework1/MatrixSorting/MatrixSorting.sln
  - solution_path: sem2/homework1/Sorting/Sorting.sln
  - solution_path: sem2/homework1/Spiral/Spiral.sln

build_script:
  - msbuild %solution_path%

test_script:
  - dotnet test sem2/homework1/Factorial/Factorial.sln
  - dotnet test sem2/homework1/Fibonacci/Fibonacci.sln
  - dotnet test sem2/homework1/MatrixSorting/MatrixSorting.sln
  - dotnet test sem2/homework1/Sorting/Sorting.sln
  - dotnet test sem2/homework1/Spiral/Spiral.sln
